# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import keycodes_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='remote.proto',
  package='',
  serialized_pb='\n\x0cremote.proto\x1a\x0ekeycodes.proto\"~\n\rRemoteMessage\x12\x17\n\x0fsequence_number\x18\x01 \x01(\r\x12(\n\x0frequest_message\x18\x02 \x01(\x0b\x32\x0f.RequestMessage\x12*\n\x10response_message\x18\x03 \x01(\x0b\x32\x10.ResponseMessage\"\xe9\x01\n\x0eRequestMessage\x12$\n\x11key_event_message\x18\x01 \x01(\x0b\x32\t.KeyEvent\x12(\n\x13mouse_event_message\x18\x02 \x01(\x0b\x32\x0b.MouseEvent\x12(\n\x13mouse_wheel_message\x18\x03 \x01(\x0b\x32\x0b.MouseWheel\x12\x1b\n\x0c\x64\x61ta_message\x18\x04 \x01(\x0b\x32\x05.Data\x12!\n\x0f\x63onnect_message\x18\x05 \x01(\x0b\x32\x08.Connect\x12\x1d\n\rfling_message\x18\x06 \x01(\x0b\x32\x06.Fling\"Z\n\x0fResponseMessage\x12\x1b\n\x0c\x64\x61ta_message\x18\x01 \x01(\x0b\x32\x05.Data\x12*\n\x14\x66ling_result_message\x18\x03 \x01(\x0b\x32\x0c.FlingResult\";\n\x08KeyEvent\x12\x16\n\x07keycode\x18\x01 \x02(\x0e\x32\x05.Code\x12\x17\n\x06\x61\x63tion\x18\x02 \x02(\x0e\x32\x07.Action\".\n\nMouseEvent\x12\x0f\n\x07x_delta\x18\x01 \x02(\x05\x12\x0f\n\x07y_delta\x18\x02 \x02(\x05\"0\n\nMouseWheel\x12\x10\n\x08x_scroll\x18\x01 \x02(\x05\x12\x10\n\x08y_scroll\x18\x02 \x02(\x05\"/\n\x07\x43onnect\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\"\x14\n\x05\x46ling\x12\x0b\n\x03uri\x18\x01 \x02(\t\"\"\n\x04\x44\x61ta\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\t\"V\n\x0b\x46lingResult\x12#\n\x06result\x18\x01 \x02(\x0e\x32\x13.FlingResult.Result\"\"\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x42 \n\x12\x63om.google.anymoteB\x08MessagesH\x03')



_FLINGRESULT_RESULT = descriptor.EnumDescriptor(
  name='Result',
  full_name='FlingResult.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=806,
  serialized_end=840,
)


_REMOTEMESSAGE = descriptor.Descriptor(
  name='RemoteMessage',
  full_name='RemoteMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sequence_number', full_name='RemoteMessage.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request_message', full_name='RemoteMessage.request_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='response_message', full_name='RemoteMessage.response_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=158,
)


_REQUESTMESSAGE = descriptor.Descriptor(
  name='RequestMessage',
  full_name='RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key_event_message', full_name='RequestMessage.key_event_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mouse_event_message', full_name='RequestMessage.mouse_event_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mouse_wheel_message', full_name='RequestMessage.mouse_wheel_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_message', full_name='RequestMessage.data_message', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='connect_message', full_name='RequestMessage.connect_message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fling_message', full_name='RequestMessage.fling_message', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=161,
  serialized_end=394,
)


_RESPONSEMESSAGE = descriptor.Descriptor(
  name='ResponseMessage',
  full_name='ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data_message', full_name='ResponseMessage.data_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fling_result_message', full_name='ResponseMessage.fling_result_message', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=396,
  serialized_end=486,
)


_KEYEVENT = descriptor.Descriptor(
  name='KeyEvent',
  full_name='KeyEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='keycode', full_name='KeyEvent.keycode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='KeyEvent.action', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=488,
  serialized_end=547,
)


_MOUSEEVENT = descriptor.Descriptor(
  name='MouseEvent',
  full_name='MouseEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x_delta', full_name='MouseEvent.x_delta', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_delta', full_name='MouseEvent.y_delta', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=549,
  serialized_end=595,
)


_MOUSEWHEEL = descriptor.Descriptor(
  name='MouseWheel',
  full_name='MouseWheel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x_scroll', full_name='MouseWheel.x_scroll', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y_scroll', full_name='MouseWheel.y_scroll', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=597,
  serialized_end=645,
)


_CONNECT = descriptor.Descriptor(
  name='Connect',
  full_name='Connect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='device_name', full_name='Connect.device_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='Connect.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=647,
  serialized_end=694,
)


_FLING = descriptor.Descriptor(
  name='Fling',
  full_name='Fling',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uri', full_name='Fling.uri', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=696,
  serialized_end=716,
)


_DATA = descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Data.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='Data.data', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=718,
  serialized_end=752,
)


_FLINGRESULT = descriptor.Descriptor(
  name='FlingResult',
  full_name='FlingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='FlingResult.result', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FLINGRESULT_RESULT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=754,
  serialized_end=840,
)

_REMOTEMESSAGE.fields_by_name['request_message'].message_type = _REQUESTMESSAGE
_REMOTEMESSAGE.fields_by_name['response_message'].message_type = _RESPONSEMESSAGE
_REQUESTMESSAGE.fields_by_name['key_event_message'].message_type = _KEYEVENT
_REQUESTMESSAGE.fields_by_name['mouse_event_message'].message_type = _MOUSEEVENT
_REQUESTMESSAGE.fields_by_name['mouse_wheel_message'].message_type = _MOUSEWHEEL
_REQUESTMESSAGE.fields_by_name['data_message'].message_type = _DATA
_REQUESTMESSAGE.fields_by_name['connect_message'].message_type = _CONNECT
_REQUESTMESSAGE.fields_by_name['fling_message'].message_type = _FLING
_RESPONSEMESSAGE.fields_by_name['data_message'].message_type = _DATA
_RESPONSEMESSAGE.fields_by_name['fling_result_message'].message_type = _FLINGRESULT
_KEYEVENT.fields_by_name['keycode'].enum_type = keycodes_pb2._CODE
_KEYEVENT.fields_by_name['action'].enum_type = keycodes_pb2._ACTION
_FLINGRESULT.fields_by_name['result'].enum_type = _FLINGRESULT_RESULT
_FLINGRESULT_RESULT.containing_type = _FLINGRESULT;
DESCRIPTOR.message_types_by_name['RemoteMessage'] = _REMOTEMESSAGE
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['KeyEvent'] = _KEYEVENT
DESCRIPTOR.message_types_by_name['MouseEvent'] = _MOUSEEVENT
DESCRIPTOR.message_types_by_name['MouseWheel'] = _MOUSEWHEEL
DESCRIPTOR.message_types_by_name['Connect'] = _CONNECT
DESCRIPTOR.message_types_by_name['Fling'] = _FLING
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['FlingResult'] = _FLINGRESULT

class RemoteMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOTEMESSAGE
  
  # @@protoc_insertion_point(class_scope:RemoteMessage)

class RequestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTMESSAGE
  
  # @@protoc_insertion_point(class_scope:RequestMessage)

class ResponseMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSEMESSAGE
  
  # @@protoc_insertion_point(class_scope:ResponseMessage)

class KeyEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYEVENT
  
  # @@protoc_insertion_point(class_scope:KeyEvent)

class MouseEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOUSEEVENT
  
  # @@protoc_insertion_point(class_scope:MouseEvent)

class MouseWheel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOUSEWHEEL
  
  # @@protoc_insertion_point(class_scope:MouseWheel)

class Connect(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECT
  
  # @@protoc_insertion_point(class_scope:Connect)

class Fling(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLING
  
  # @@protoc_insertion_point(class_scope:Fling)

class Data(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATA
  
  # @@protoc_insertion_point(class_scope:Data)

class FlingResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLINGRESULT
  
  # @@protoc_insertion_point(class_scope:FlingResult)

# @@protoc_insertion_point(module_scope)
